### ISSUE TITLE
您好，请问一下py库的requirements.txt的文本在哪呢

### ISSUE THREAD

**Issue by Rubi1iXD** [laohuan12138/Ransomware-testing#1]
您好，请问一下py库的requirements.txt的文本在哪呢

**Comment by laohuan12138** [comment]
放忘记了，已经放在项目了

**Comment by Rubi1iXD** [comment]
好的谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月12日(星期天) 晚上9:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [laohuan12138/Ransomware-testing] 您好，请问一下py库的requirements.txt的文本在哪呢 (Issue #1)





 
放忘记了，已经放在项目了

**Comment by laohuan12138** [comment]
> 您好，请问一下py库的requirements.txt的文本在哪呢

忘记了，已经放了
